# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_plugin "vagrant-omnibus"

chef_config  = (JSON.parse(File.read("chef.json")))['chef']

Vagrant.configure("2") do |config|
  #config.vm.box = "opscode_ubuntu-14.04"
  config.vm.box = "bento/centos-7.2"
  #config.vm.box_url = "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box"

  config.omnibus.chef_version = :latest
  config.vm.provision :chef_client do |chef|
    chef.provisioning_path = chef_config[':provisioning_path']
    chef.chef_server_url = chef_config[':chef_server_url']
    chef.validation_client_name = chef_config[':validation_client_name']
    chef.validation_key_path = chef_config[':validation_key_path']
    chef.node_name = chef_config[':node_name']
  end
  config.vm.provider :virtualbox do |vb|
    vb.gui = false
  end
end