# -*- mode: ruby -*-
# vi: set ft=ruby :

# Deprecated just raise error if it's missing
#Vagrant.require_plugin "vagrant-omnibus"

chef_config  = (JSON.parse(File.read("chef.json")))['chef']

Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.2"

  config.vm.network :private_network, ip: "192.168.33.10"
  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.omnibus.chef_version = :latest
  config.vm.provision :chef_client do |chef|
    chef.provisioning_path = chef_config[':provisioning_path']
    chef.chef_server_url = chef_config[':chef_server_url']
    chef.validation_client_name = chef_config[':validation_client_name']
    chef.validation_key_path = chef_config[':validation_key_path']
    chef.client_key_path = chef_config[':client_key_path']
    chef.environment = chef_config[':environment']
    chef.node_name = chef_config[':node_name']
  end
  config.vm.provider :virtualbox do |vb|
    vb.gui = false
  end
end