# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.define "jenkins" do |jenkins|
        jenkins.vm.box = "ubuntu/trusty64"
        jenkins.vm.network "private_network", ip: "192.168.0.252"
        jenkins.vm.hostname = "jenkins"

        jenkins.vm.provider "virtualbox" do |v|
            v.memory = 4096
            v.cpus = 2
        end

        jenkins.vm.provision "shell", path: "bootstrap-jenkins.sh"
    end
end