Vagrant.configure(2) do |config|
	config.vm.define "devops-go-box" do |box|
		box.vm.box = "ubuntu/xenial64"
    		#box.vm.network "private_network", ip: "192.168.256.0"
    		#box.vm.hostname = "devops-go-box"
      		box.vm.provision "shell", path: "scripts/bootstrap.sh"
    		box.vm.provider "virtualbox" do |v|
    		  v.memory = 4096
    		  v.cpus = 2
    		end
	end
end