# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

   config.vm.define "ansible" do |ansible|
      ansible.vm.box = "ubuntu/trusty64"
      ansible.vm.network "private_network", ip: "192.168.0.254"
      ansible.vm.network "forwarded_port", guest: 22, host: 2200
      ansible.vm.hostname = "ansible"
      ansible.vm.synced_folder "share", "/home/vagrant/share/"
      ansible.vm.provision "shell", path: "ansible-script.sh"
    end

   config.vm.define "webserver" do |webserver|
      webserver.vm.box = "ubuntu/trusty64"
      webserver.vm.network "private_network", ip: "192.168.0.2"
      webserver.vm.hostname = "webserver"
      webserver.vm.synced_folder "share", "/home/vagrant/share"
      webserver.vm.provision "shell", path: "webserver-script.sh"

   end
end